name: "OpenVPN Connect"
description: "Connect To OpenVPN Server"
branding:
  icon: "lock"
  color: "yellow"
inputs:
  config_file:
    description: "Location of OpenVPN client config file"
    required: true
  username:
    description: "Username"
    required: false
  password:
    description: "Password"
    required: false
  private_key_password:
    description: "Private Key Password"
    required: false
  tls_auth_key:
    description: "Pre-shared group key for TLS Auth"
    required: false
  tls_crypt_key:
    description: "Pre-shared group key for TLS Crypt"
    required: false
  tls_crypt_v2_key:
    description: "Per-client key for TLS Crypt V2"
    required: false
  client_key:
    description: "Local peer's private key"
    required: false
  echo_config:
    description: "Print the OpenVPN configuration file"
    required: false
    default: "true"
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
